language: python

install:
- curl -sSL https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb > hugo.deb
- sudo dpkg -i hugo.deb

script:
- hugo --gc --minify --enableGitInfo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  keep-history: true
  verbose: true
  on:
    branch: master
