baseURL = "https://clux.github.io/probes/"
title = "probes"
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
canonifyURLs= true
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "dracula"

[Params]
  useHLJS = false
  useKatex = false # custom loading it
  #commit = "https://github.com/clux/probes/tree"
  showRelatedPosts = true
  #readingTime = true
  subtitle = "into the brain of eirik"

[Author]
  name = "clux"
  github = "clux"
  twitter = "sszynrae"
  reddit = "clux"
  email = "sszynrae@gmail.com"
  linkedin = "eirik-albrigtsen-b279863a"
  strava = "4073612536"
  youtube = "channel/UCLpykMxkxuPUR9CciheipZg"
  steam = "sszynrae"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
