baseURL = "https://clux.dev/"
title = "probes"
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
canonifyURLs= true
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "dracula"

[markup.goldmark.renderer]
  unsafe = true

[Params]
  useHLJS = false
  #commit = "https://github.com/clux/probes/tree"
  showRelatedPosts = true
  #readingTime = true
  subtitle = "into the brain of eirik"

[Author]
  name = "clux"
  github = "clux"
  reddit = "clux"
  email = "sszynrae@gmail.com"
  linkedin = "🗑-eirik-albrigtsen-b279863a"
  strava = "49770219"
  discord = "tokio"
  youtube = "channel/UCLpykMxkxuPUR9CciheipZg"
  mastodon = "https://hachyderm.io/@clux"
  steam = "sszynrae"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
